### ISSUE TITLE
Chronological based on quality

### ISSUE THREAD

**Issue by rohitmi0023** [leonardomso/33-js-concepts#139]
Well I have found this repo to be very useful but it seems to me that the items in the list are not in any chronological order. Correct me if wrong.
And I feel that it should have something like top 3 that are very much essential and should not be left out.

**Comment by leonardomso** [comment]
Yes, they're not on chronological order list. What would be your suggestion for a top 3? Maybe we could do that in the future.

**Comment by rohitmi0023** [comment]
Its the top 3 of resources(articles/videos) that I was thinking and not the top 3 topics. As I have seen that sometimes the most valuable resources are at the bottom and will be left out by the most of the people.

**Comment by zeitchef** [comment]
@rohitmi0023 The problem is who get's to decide which resources are the most valuable? I would guess the 3 most valuable to you could easily the 3 least valuable to someone else.

I do think there are far too many resources for some of these topics, and would love to see a "top 5" for all the concepts. But this would have to be what the community thinks are the most valuable as a whole.

**Comment by leonardomso** [comment]
@zeitchef I agree with you. I think that an important topic for a developer depends on what problem he/she is trying to solve in that specific moment. I'm planning to do a repagination in the repo and filter some topics that have too many resources, and maintain only the most high-quality resources.

**Comment by rohitmi0023** [comment]
@zeitchef What I am trying to point about the top 3/5 resources is kinda similar to what we have editor's choice in google playstore. Those apps are the preferred ones by the editor's and doesn't comments on the others apps.
Yes, I agree with you totally that it is the community that eventually will decide about the more valuable resources.
