### ISSUE TITLE
No Sanskrit(संस्कृत) Translation

### ISSUE THREAD

**Issue by meaviral17** [leonardomso/33-js-concepts#399]

**Comment by Akshayp02** [comment]
I would like to work on this issue. Can you please assign me this issue with a description so that I can understand what I need to do? I have also noticed #400, but there seems to be a problem, possibly related to errors while adding files to Git.


![image](https://github.com/leonardomso/33-js-concepts/assets/95123298/844164e8-879e-4b85-bcfd-85a12ccd4f57)
