### ISSUE TITLE
Add a New Video Link in Under. 6. Function Scope, Block Scope and Lexical Scope

### ISSUE THREAD

**Issue by kumar007ambi** [leonardomso/33-js-concepts#508]
I want to add add new Video link which helps to understands Scope, Block Scope and Lexical Scope topics more consisely,Please assign this issue to resolve @leonardomso

**Comment by guruprasath-v** [comment]
Can i take this?

**Comment by AhmadHassan71** [comment]
Can I take this?

**Comment by RachitSahu26** [comment]
i have completed this issue

**Comment by kumar007ambi** [comment]
@leonardomso I have participated in hactoberfest previous year also where rules states that who will raise the issue at first he will be assigned, then assigned participant will resolve the issue, if assigned person is unable to complete it then you can assign it other participant.This is is the rule if you are following the rule then it is okay, beacuses  I have raised issues another projects in hactoberfest and I will wait for tagging and assigning.

**Comment by RachitSahu26** [comment]
@kumar007ambi hey rule is not only this if maintainer is not assigning to you that you will fix this issue so you should take a action and try to fix it Otherwise, you will be kept waiting , and one thing more its very small and easy then i fixed it under 15 minute if still you will do as same then i think can't fix any issue if you have a confidence to fix this issue then do so fast

**Comment by kumar007ambi** [comment]
@RachitSahu26 For your kinf information if rules are not followed then everyone makes every repo as spaaammmm,and if you want to fix more issue just go to some big repos, just try to fix by own without assignig you,if you will be succeded in this process then ping me.
